# Generated by Django 4.1.13 on 2024-02-01 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('narration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_received_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bank_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('passport_no', models.CharField(max_length=20)),
                ('passport_expiration_date', models.DateField()),
                ('emirates_id', models.CharField(max_length=20)),
                ('id_expiration_date', models.DateField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('joining_date', models.DateField()),
                ('job_role', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vat', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_allowed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('vat', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_allowed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('num_users', models.PositiveIntegerField()),
                ('vat_remainder', models.BooleanField(default=False)),
                ('employee_transaction_window', models.BooleanField(default=False)),
                ('license_expiration_reminder', models.BooleanField(default=False)),
                ('employee_visa_expiration_reminder', models.BooleanField(default=False)),
                ('employee_passport_expiration_reminder', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_expiration', models.DateField()),
                ('license_file', models.FileField(upload_to='license_files/')),
                ('phone_number', models.CharField(max_length=20)),
                ('vat_percentage', models.FloatField()),
                ('vat_number', models.CharField(max_length=50)),
                ('vat_submission_date', models.DateField()),
                ('vat_certificate', models.FileField(upload_to='vat_certificates/')),
                ('address', models.TextField()),
                ('license_expiration_reminder_days', models.PositiveIntegerField()),
                ('vat_submission_date_reminder_days', models.PositiveIntegerField()),
                ('employee_visa_expiration_reminder_days', models.PositiveIntegerField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='ezshopapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('modules', models.ManyToManyField(to='ezshopapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narration', models.TextField()),
                ('receipt_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.receipttype')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('narration', models.TextField()),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.expensetype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('service', 'Service Transaction'), ('service_and_product', 'Service & Product Transaction')], max_length=20)),
                ('tip_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_option', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=10)),
                ('product_transactions', models.ManyToManyField(blank=True, related_name='product_transactions', to='ezshopapp.product')),
                ('service_transactions', models.ManyToManyField(blank=True, related_name='service_transactions', to='ezshopapp.service')),
            ],
        ),
    ]
