# Generated by Django 4.1.13 on 2024-03-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0001_initial'),
    ]

    operations = [
    ]
