# Generated by Django 4.1.13 on 2024-03-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, null=True)),
                ('license_number', models.CharField(max_length=255)),
                ('license_expiration', models.DateField(null=True)),
                ('license_upload', models.FileField(upload_to='licenses')),
                ('shop_phone_number', models.CharField(max_length=25)),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_number', models.CharField(max_length=255)),
                ('vat_submission_date_1', models.DateField(null=True)),
                ('vat_submission_date_2', models.DateField(null=True)),
                ('vat_submission_date_3', models.DateField(null=True)),
                ('vat_certificate_upload', models.FileField(upload_to='vat_certificates')),
                ('address', models.TextField()),
                ('license_expiration_reminder_days', models.PositiveIntegerField(verbose_name='License Expiration Reminder (days)')),
                ('vat_submission_date_reminder_days', models.PositiveIntegerField(verbose_name='VAT Submission Date Reminder (days)')),
                ('employee_visa_expiration_reminder_days', models.PositiveIntegerField(verbose_name='Employee Visa Expiration Reminder (days)')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayClosingAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_services', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeetransaction',
            name='tip_received',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='employee_visa_expiration_reminder_days',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='license_expiration',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='license_expiration_reminder_days',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='license_file',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_certificate',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_number',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_percentage',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_submission_date',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_submission_date_reminder_days',
        ),
        migrations.AddField(
            model_name='bank',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.bank'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipttransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipttype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='admin_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mite Admin User'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ezshopapp.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('service', 'Service Transaction'), ('product', 'Product Transaction'), ('service_and_product', 'Service & Product Transaction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(default=None, to='ezshopapp.module'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_passport_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='Employee Passport Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_visa_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='Employee Visa Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='license_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='License Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='num_users',
            field=models.PositiveIntegerField(verbose_name='Number of Users'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='vat_remainder',
            field=models.BooleanField(default=False, verbose_name='VAT Reminder'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.shop'),
        ),
        migrations.CreateModel(
            name='SalesByStaffItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('employee_id', models.IntegerField(null=True, verbose_name='Employee ID')),
                ('pquantity', models.PositiveIntegerField(null=True, verbose_name='Product Quantity')),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Product Price')),
                ('squantity', models.PositiveIntegerField(null=True, verbose_name='Service Quantity')),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Service Price')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20, verbose_name='Payment Method')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.product', verbose_name='Product')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='SalesByAdminItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.sale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.service')),
            ],
        ),
        migrations.CreateModel(
            name='SaleByAdminService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_method', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.service')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='services',
            field=models.ManyToManyField(through='ezshopapp.SaleItem', to='ezshopapp.service'),
        ),
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_services', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=8)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_collection', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employeetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(default='ezshop@2024', max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.businessprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
