# Generated by Django 4.1.13 on 2024-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebystaffservice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=100),
        ),
    ]
