# Generated by Django 4.1.13 on 2024-03-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0002_auto_20240331_1958'),
    ]

    operations = [
    ]
