# Generated by Django 4.1.13 on 2024-02-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0002_sale_saleitem_sale_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesbyAdminItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee')),
            ],
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.product'),
        ),
        migrations.CreateModel(
            name='SalesbyAdminItemSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.saleitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.salesbyadminitem')),
            ],
        ),
    ]
