# Generated by Django 4.1.13 on 2024-03-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0002_businessprofile_dayclosingadmin_modules_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebyadminservice',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='salesbyadminitem',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee', verbose_name='Employee'),
        ),
    ]
