# Generated by Django 4.1.13 on 2024-03-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0002_businessprofile_dayclosingadmin_modules_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbystaffitemservice',
            name='employee_id',
        ),
    ]
