# Generated by Django 5.0.4 on 2024-05-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0002_bank_business_profile_bankdeposit_business_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttransaction',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
