# Generated by Django 4.1.13 on 2024-03-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0003_remove_salesbystaffitemservice_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbystaffitemservice',
            name='employee_id',
            field=models.IntegerField(null=True, verbose_name='Employee ID'),
        ),
    ]
