# Generated by Django 5.0.4 on 2024-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0003_receipttransaction_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
