# Generated by Django 4.1.13 on 2024-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0003_salesbyadminitem_saleitem_price_saleitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_services', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=8)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_collection', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
