# Generated by Django 4.1.13 on 2024-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0004_dayclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclosing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
