# Generated by Django 5.0.4 on 2024-05-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0004_dailysummary_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebyadminservice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
