# Generated by Django 4.1.13 on 2024-03-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0004_salesbystaffitemservice_itemtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayclosing',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee'),
        ),
    ]
