# Generated by Django 5.0.4 on 2024-05-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0005_salebyadminservice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbyadminitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
