# Generated by Django 4.1.13 on 2024-03-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0005_alter_salesbystaffitemservice_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbystaffitemservice',
            name='employee_id',
        ),
    ]
