# Generated by Django 4.1.13 on 2024-03-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0005_alter_dayclosing_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebyadminservice',
            name='employee',
        ),
        migrations.AddField(
            model_name='salebyadminservice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
        migrations.CreateModel(
            name='SaleByStaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_method', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee', verbose_name='Employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.service')),
            ],
        ),
    ]
