# Generated by Django 4.1.13 on 2024-02-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0006_salebyadminservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesbyadminitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesbyadminitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.saleitem'),
        ),
        migrations.AddField(
            model_name='salesbyadminitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesbyadminitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salesbyadminitem',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesbyadminitem',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20),
        ),
        migrations.DeleteModel(
            name='SalesbyAdminItemSaleItem',
        ),
    ]
