# Generated by Django 5.0.4 on 2024-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0006_salesbyadminitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebystaffitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
