# Generated by Django 4.1.13 on 2024-03-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0007_salebyadminservice_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebyadminservice',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Service Quantity'),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='salebystaffservice',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
