# Generated by Django 5.0.4 on 2024-05-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0007_salebystaffitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebystaffservice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
