# Generated by Django 4.1.13 on 2024-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0008_alter_salebyadminservice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebyadminservice',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
