# Generated by Django 4.1.13 on 2024-02-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0008_alter_salesbyadminitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesbyadminitem',
            name='tip',
        ),
    ]
