# Generated by Django 4.1.13 on 2024-03-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0009_alter_salebyadminservice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
