# Generated by Django 5.0.4 on 2024-05-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0009_salesbystaffitemservice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclosingadmin',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
