# Generated by Django 5.0.4 on 2024-05-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0010_dayclosingadmin_business_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
