# Generated by Django 4.1.13 on 2024-03-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0010_dailysummary_opening_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
    ]
