# Generated by Django 4.1.13 on 2024-02-17 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezshopapp', '0011_remove_salesbystaffitemservice_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiration', models.DateField()),
                ('license_upload', models.ImageField(upload_to='license/')),
                ('shop_phone_number', models.CharField(max_length=15)),
                ('vat_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_number', models.CharField(max_length=50, unique=True)),
                ('vat_submission_date', models.DateField()),
                ('vat_certificate_upload', models.ImageField(upload_to='vat_certificate/')),
                ('address', models.TextField()),
                ('license_expiration_reminder_days', models.PositiveIntegerField()),
                ('vat_submission_date_reminder_days', models.PositiveIntegerField()),
                ('employee_visa_expiration_reminder_days', models.PositiveIntegerField()),
                ('admins', models.ManyToManyField(related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
