# Generated by Django 4.1.13 on 2024-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0014_rename_service_salebystaffservice_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebystaffservice',
            old_name='service_id',
            new_name='service',
        ),
    ]
