# Generated by Django 4.1.13 on 2024-03-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0015_rename_service_id_salebystaffservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebystaffservice',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee', verbose_name='Employee'),
        ),
    ]
