# Generated by Django 4.1.13 on 2024-02-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0015_adminprofile_password_alter_adminprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='admins',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='license_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='license_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='license_upload',
            field=models.FileField(upload_to='licenses'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='shop_phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='vat_certificate_upload',
            field=models.FileField(upload_to='vat_certificates'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='vat_number',
            field=models.CharField(max_length=255),
        ),
    ]
