# Generated by Django 4.1.13 on 2024-02-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0016_remove_businessprofile_admins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='shop_phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
