# Generated by Django 4.1.13 on 2024-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0017_alter_businessprofile_shop_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='mobile',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
