# Generated by Django 4.1.13 on 2024-02-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0018_alter_adminprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadmin',
            name='license_file',
            field=models.FileField(upload_to='licenses/'),
        ),
    ]
