# Generated by Django 4.1.13 on 2024-03-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0018_rename_salesbystaffitem_salebystaffitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebystaffitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total Amount'),
        ),
    ]
