# Generated by Django 4.1.13 on 2024-02-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0019_alter_shopadmin_license_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebyadminservice',
            name='date',
        ),
        migrations.AddField(
            model_name='salebyadminservice',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.sale'),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='tip',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
