# Generated by Django 4.1.13 on 2024-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0019_salebystaffitem_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayclosingadmin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='approved', max_length=10),
        ),
    ]
