# Generated by Django 4.1.13 on 2024-02-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0020_remove_salebyadminservice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebyadminservice',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.sale'),
        ),
    ]
