# Generated by Django 4.1.13 on 2024-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0021_alter_salebyadminservice_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
