# Generated by Django 4.1.13 on 2024-03-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0021_alter_dayclosing_status_alter_dayclosingadmin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
