# Generated by Django 4.1.13 on 2024-02-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0022_alter_sale_net_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebyadminservice',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.sale'),
        ),
    ]
