# Generated by Django 4.1.13 on 2024-03-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0022_alter_employee_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclosingadmin',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
