# Generated by Django 4.1.13 on 2024-02-27 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezshopapp', '0023_alter_salebyadminservice_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebyadminservice',
            name='sale',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ezshopapp.employeetransaction'),
        ),
        migrations.AddField(
            model_name='salebyadminservice',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='employee_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_transactions', to='ezshopapp.employeetransaction'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
