# Generated by Django 4.1.13 on 2024-03-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0024_role_business_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='business_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.businessprofile'),
        ),
    ]
