# Generated by Django 4.1.13 on 2024-02-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0024_remove_salebyadminservice_sale_and_more'),
    ]

    operations = [
    ]
