# Generated by Django 4.1.13 on 2024-02-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0025_auto_20240227_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='employee_transaction',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_transactions', to='ezshopapp.employeetransaction'),
        ),
    ]
