# Generated by Django 4.1.13 on 2024-02-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0026_remove_shop_employee_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employeetransaction'),
        ),
    ]
