# Generated by Django 4.1.13 on 2024-02-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0027_alter_employee_employee_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_transaction',
            new_name='employee_transaction_id',
        ),
    ]
