# Generated by Django 4.1.13 on 2024-03-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0027_employee_business_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
