# Generated by Django 4.1.13 on 2024-02-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0028_rename_employee_transaction_employee_employee_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_transaction_id',
            new_name='employee_transaction',
        ),
        migrations.AddField(
            model_name='dayclosing',
            name='employee_transactions',
            field=models.ManyToManyField(to='ezshopapp.employeetransaction'),
        ),
        migrations.AlterField(
            model_name='dayclosing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
