# Generated by Django 4.1.13 on 2024-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0028_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='employee_passport_expiration_reminder',
            field=models.BooleanField(default=True, verbose_name='Employee Passport Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_transaction_window',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_visa_expiration_reminder',
            field=models.BooleanField(default=True, verbose_name='Employee Visa Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='license_expiration_reminder',
            field=models.BooleanField(default=True, verbose_name='License Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='vat_remainder',
            field=models.BooleanField(default=True, verbose_name='VAT Reminder'),
        ),
    ]
