# Generated by Django 4.1.13 on 2024-03-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0029_alter_shop_employee_passport_expiration_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
