# Generated by Django 4.1.13 on 2024-02-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0030_remove_employee_employee_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayclosing',
            name='tip',
        ),
    ]
