# Generated by Django 4.1.13 on 2024-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0030_module_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(choices=[('/sale/dayclosing/', 'Day Closing'), ('/dayclosing/admin/', 'Admin Day Closing'), ('/sale/sales-by-staff-item-service/', 'Sales by Staff - Product/Service'), ('/sale/sales-by-staff-service/', 'Sales by Staff - Service'), ('/sale/sales-by-staff-item/', 'Sales by Staff - Product'), ('/sale/day-closing-report/', 'Day Closing Report'), ('/sale/sales-report/', 'Sales Report')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='url',
            field=models.CharField(choices=[('/sale/dayclosing/', 'Day Closing'), ('/dayclosing/admin/', 'Admin Day Closing'), ('/sale/sales-by-staff-item-service/', 'Sales by Staff - Product/Service'), ('/sale/sales-by-staff-service/', 'Sales by Staff - Service'), ('/sale/sales-by-staff-item/', 'Sales by Staff - Product'), ('/sale/day-closing-report/', 'Day Closing Report'), ('/sale/sales-report/', 'Sales Report')], max_length=150, null=True),
        ),
    ]
