# Generated by Django 4.1.13 on 2024-02-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0031_remove_dayclosing_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayclosing',
            name='employee_transactions',
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='day_closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.dayclosing'),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee'),
        ),
    ]
