# Generated by Django 4.1.13 on 2024-03-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0032_remove_dayclosing_employee_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclosing',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee'),
        ),
    ]
