# Generated by Django 4.1.13 on 2024-03-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0034_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('service', 'Service Transaction'), ('product', 'Product Transaction'), ('service_and_product', 'Service & Product Transaction')], max_length=20),
        ),
    ]
