# Generated by Django 4.1.13 on 2024-03-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0035_alter_employeetransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.shop'),
        ),
    ]
