# Generated by Django 4.1.13 on 2024-03-05 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0040_alter_businessprofile_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosingAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_services', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
            ],
        ),
    ]
