# Generated by Django 4.1.13 on 2024-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0042_remove_employee_password_remove_employee_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='employee_visa_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='Employee Visa Expiration Remainder (days)'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='license_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='License Expiration Remainder (days)'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='vat_submission_date_reminder_days',
            field=models.PositiveIntegerField(verbose_name='VAT Submission Date Remainder (days)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_passport_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='Employee Passport Expiration Remainder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_visa_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='Employee Visa Expiration Remainder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='license_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='License Expiration Remainder'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='employee_visa_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='Employee Visa Expiration Remainder (days)'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='license_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='License Expiration Remainder (days)'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='vat_submission_date_reminder_days',
            field=models.PositiveIntegerField(verbose_name='VAT Submission Date Remainder (days)'),
        ),
    ]
