# Generated by Django 4.1.13 on 2024-03-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0043_alter_businessprofile_employee_visa_expiration_reminder_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dayclosing',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dayclosingadmin',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipttransaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipttype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salebyadminservice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salesbyadminitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salesbystaffitemservice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='employee_visa_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='Employee Visa Expiration Reminder (days)'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='license_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='License Expiration Reminder (days)'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='vat_submission_date_reminder_days',
            field=models.PositiveIntegerField(verbose_name='VAT Submission Date Reminder (days)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_passport_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='Employee Passport Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='employee_visa_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='Employee Visa Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='license_expiration_reminder',
            field=models.BooleanField(default=False, verbose_name='License Expiration Reminder'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='employee_visa_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='Employee Visa Expiration Reminder (days)'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='license_expiration_reminder_days',
            field=models.PositiveIntegerField(verbose_name='License Expiration Reminder (days)'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='vat_submission_date_reminder_days',
            field=models.PositiveIntegerField(verbose_name='VAT Submission Date Reminder (days)'),
        ),
    ]
