# Generated by Django 4.1.13 on 2024-03-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0044_adminprofile_created_on_bank_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='vat_submission_date',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vat_submission_date_1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vat_submission_date_2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vat_submission_date_3',
            field=models.DateField(null=True),
        ),
    ]
