# Generated by Django 4.1.13 on 2024-03-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0045_remove_businessprofile_vat_submission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetransaction',
            name='tip_received',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='salebyadminservice',
            name='tip',
        ),
    ]
