# Generated by Django 4.1.13 on 2024-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0046_remove_employeetransaction_tip_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='vat_remainder',
            field=models.BooleanField(default=False, verbose_name='VAT Reminder'),
        ),
    ]
