# Generated by Django 4.1.13 on 2024-03-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0047_alter_shop_vat_remainder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(choices=[('shop', 'Shop'), ('business', 'Business Profile'), ('employee', 'Employee'), ('sale', 'Sale & Day Closing'), ('role', 'Role'), ('expense-type', 'Expense Type'), ('receipt-transaction', 'Receipt Transaction'), ('payment-transaction', 'Payment Transaction'), ('service', 'Service'), ('product', 'Product'), ('employee-transaction', 'Employee Transaction'), ('daily-summary', 'Daily Summary'), ('bank', 'Bank Deposit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='num_users',
            field=models.PositiveIntegerField(verbose_name='Number of Users'),
        ),
    ]
