# Generated by Django 4.1.13 on 2024-03-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0049_remove_role_modules_role_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='modules',
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(null=True, to='ezshopapp.module'),
        ),
    ]
