# Generated by Django 4.1.13 on 2024-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0052_shop_email_shop_password_shop_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Shop Name'),
        ),
    ]
