# Generated by Django 4.1.13 on 2024-03-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0053_alter_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='username',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='employee_visa_expiration_reminder_days',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='license_expiration',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='license_expiration_reminder_days',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='license_file',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_certificate',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_number',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_percentage',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_submission_date',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='vat_submission_date_reminder_days',
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='password',
            field=models.CharField(default='Mite@2024', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='username',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(default=None, to='ezshopapp.module'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='ezshopapp.shop'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
