# Generated by Django 4.1.13 on 2024-03-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0054_remove_shop_email_remove_shop_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadmin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='username',
        ),
    ]
