# Generated by Django 4.1.13 on 2024-03-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0057_alter_shopadmin_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='admin_email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.shop'),
        ),
    ]
