# Generated by Django 4.1.13 on 2024-03-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0058_shop_admin_email_alter_shopadmin_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='admin_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
