# Generated by Django 4.1.13 on 2024-03-07 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezshopapp', '0059_alter_shop_admin_email_alter_shopadmin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadmin',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='email',
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='admin_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.shop'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
