# Generated by Django 4.1.13 on 2024-03-07 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezshopapp', '0060_remove_shopadmin_created_on_remove_shopadmin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mite Admin User'),
        ),
    ]
