# Generated by Django 4.1.13 on 2024-03-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0061_alter_shopadmin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='business_profile',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
