# Generated by Django 4.1.13 on 2024-03-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0062_alter_employee_business_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='ezshopapp.shop'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='business_profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
