# Generated by Django 4.1.13 on 2024-03-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0063_alter_businessprofile_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='shop',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='name',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
