# Generated by Django 4.1.13 on 2024-03-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0064_remove_businessprofile_shop_businessprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadmin',
            name='user',
        ),
    ]
