# Generated by Django 4.1.13 on 2024-03-07 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezshopapp', '0065_remove_shopadmin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadmin',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='shopadmin',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mite Admin User'),
        ),
    ]
