# Generated by Django 4.1.13 on 2024-03-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0066_remove_shopadmin_admin_user_shopadmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
