# Generated by Django 4.1.13 on 2024-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0067_employee_password_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
