# Generated by Django 4.1.13 on 2024-03-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0068_employee_is_employee_alter_role_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetransaction',
            name='day_closing',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ezshopapp.bank'),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salebyadminservice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee'),
        ),
        migrations.AlterField(
            model_name='salesbystaffitemservice',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='salesbystaffitemservice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total'),
        ),
    ]
