# Generated by Django 4.1.13 on 2024-03-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0068_employee_is_employee_alter_role_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetransaction',
            name='day_closing',
        ),
    ]
