# Generated by Django 4.1.13 on 2024-03-09 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0069_remove_employeetransaction_day_closing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebyadminservice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezshopapp.employee'),
        ),
    ]
