# Generated by Django 4.1.13 on 2024-03-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0072_alter_salesbystaffitemservice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbystaffitemservice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total'),
        ),
    ]
