# Generated by Django 4.1.13 on 2024-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezshopapp', '0073_alter_salesbystaffitemservice_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesbystaffitemservice',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Sub Total'),
        ),
    ]
